### ISSUE TITLE
Add links to relevant projects

### ISSUE THREAD

**Issue by chauffer** [pomerium/awesome-zero-trust#1]
- https://zerotier.com
- https://zero.pritunl.com/
- https://github.com/pomerium/pomerium (:D)
- https://github.com/cogolabs/transcend
- more?

**Comment by chauffer** [comment]
- https://github.com/K4YT3X/wireguard-mesh-configurator
- https://github.com/squat/kilo
- https://github.com/key-networks/ztncui
- https://github.com/key-networks/ztncui-containerized

**Comment by chauffer** [comment]
- https://github.com/Gawen/WireHub

**Comment by desimone** [comment]
@chauffer Sorry again for the delayed response. I'm open to adding products but I'd like to come up with some categories so it's not just an unsorted list. 

Maybe you have some ideas?

**Comment by chauffer** [comment]
@desimone I think the list is short enough that a short description suffices for now. See #2

**Comment by desimone** [comment]
closed by #2
