### ISSUE TITLE
nist 800 207 url update

### ISSUE THREAD

**Issue by BlackMaria** [pomerium/awesome-zero-trust#8]
If you prefer a pr for this let me know.
The nist 207 url in the readme is now out of date, please refer to this one.

* old url [now withdrawn](https://doi.org/10.6028/NIST.SP.800-207-draft)
* to be replaced by https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-207-draft2.pdf

thanks for this repo.

**Comment by desimone** [comment]
@BlackMaria PR would be greatly appreciated if you don't mind, and thank you good catch.

**Comment by desimone** [comment]
Closed with #9 , thank you @BlackMaria
